### ISSUE TITLE
Handle "config.contents is not iterable"

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/procheck#1]
# Overview
The action displays error when config.contents is:
1. Does not exists
2. Not an array
3. Is an array, but do not have minimal 1 array item

# How to Reproduce

1. Create a config like this:
`[
  {
    "filePath": "./eslint.yml",
  }
]`
2. Run the action with the config

# Output
`TypeError: config.contents is not iterable`
![image](https://user-images.githubusercontent.com/16670475/100974752-69f15e00-356f-11eb-90ba-ca9aeca86eb5.png)

**Comment by kevin-hyperjump** [comment]
PR was closed #7
